import requests

url = "https://linkedmatrix.resourceinn.com/api/v1/directives/markAttendance"

headers = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZjU0NjFiZTVhNDgxYzJhMGQ3OWQwNjExOGE4ODIwYzdmMTA5Y2FlNzAzMWMxYWMyYWNjYjIxNDcwN2Q4NWIyMzg3OGY5MTIyYjgxNGIzNjQiLCJpYXQiOjE3MzEzMDk1MzcuNTIzODM3LCJuYmYiOjE3MzEzMDk1MzcuNTIzODM4LCJleHAiOjE3MzEzOTU5MzcuNTE2MTcyLCJzdWIiOiJhZWJiYTg2MS1lNDYwLTQ4ZWItODNlNS04MTM0MzhmMGQ4NWEiLCJzY29wZXMiOlsib25seS12MS1hY2Nlc3MiXX0.VSPbLjDdXBXHvGh6b3tVmBPIJY-pxgdhh35IP_HeICbwT_KTlRjJxfupaMMo0cRdGAgbTUB4R12HRX2FuAOWmmyT7NoB8P_GvLHsQNy0evbG5Mz-b4JFyzbAq-umn-ubOK89AJDMchiykZkM4LAtZ1aliOJVw9FWcjFoF-qXPreT3GA3xLoEeGD_t9a6ILa2sJr32igI2gdXJafMROjvDFgJIrVhOLloLENp56UCtixfSTiaX4Oui5Zw41YVSMReC-TuZL02HZpTSKhyxlcHzZBPwALzkHQF3K8h3mS734hgffpyzWicQjFOlCh5d1ZYhd8vfoYR0OG6afO6wGoyUOI3EL76kAhniG9E2RA4l__i-rXwJRDKlJoK3KHmId20MYmBt-0ti7nJZiIUetqnYoTn6sNDdeflGuGwZnPbcs75iWHthWj6FBHXLKRkWBcrUCaUh4S3L6KjQB4V9TvPhCi_nUOCfqega9ay2vudlvfhGqsNiKjlPrvqKKuX-kIk5ylbHwIBqFdKLkYIQNqebAb9af-s22cT0Nd0D_kd7IUMC-yOZqVMF3xh8QZnfD171AhVTzmLPk3zeb86hPj94s0BiyRHqnIMIVytPY24wpZ9YUtotrhiePvujFJvHQWK2vMV8yDxfY-GTiRTtEdd9qnO-p8yMdO4136_Iq_IYck",
    "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryLlz6sJ56J5TaAiKJ",
    "cookie": "_ga=GA1.1.1127918565.1731309533; laravel_session=uoPPixE9jc366lkEmtWXXKvebgcGGRd6UxhHu3DC; _ga_YXXBVRH8F5=GS1.1.1731309532.1.1.1731309542.0.0.0; cf_clearance=8JOO7o_SuH13f16E1Q.E1ndkEHn.DYpeYYXCZD8qvT4-1731309542-1.2.1.1-C9kTGjWcWHKzRLOnJ3HstlkSPIWK68Qq1CC01ibLVWzp9AOYZedORHWrLNqcHIM96sSz66vdwEPvW2ryhOOB17jB2elyEjMQROb0zkC6uB_JkArgsjNESQunF351R4J3iAAMFvACnyjye_5OIFqwJVrXwgd6nGrr7GsajgN4D_MjnFvjFEUkjFY6_ngaASR.U3cZjLHgt9G6IUKDoz27QHrq3SZ3J6ZiixBkZ7pL8teecoSzqAg1y5.wRC_9lAmY8H_bbK5agltpRa7nDw2cUYKArGY_Ke9oWXM88njHvIF2dOaftznYWRnRlVSl.dTzqd.CVe5iLqdgM92qmJ6Ol_WBlEB1ODhnPwgGdteJNHHKHX4C2YzP8webkXXoVWt9",
    "origin": "https://linkedmatrix.resourceinn.com",
    "priority": "u=1, i",
    "referer": "https://linkedmatrix.resourceinn.com/",
    "sec-ch-ua": '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36",
    "version-code": "417",
    "version-no": "4.1.7",
}

data = """------WebKitFormBoundaryLlz6sJ56J5TaAiKJ
Content-Disposition: form-data; name="mark_attendance"

{
    "breaks": [
        {
            "id": 1,
            "name": "Default",
            "start": "Break Out",
            "end": "Break In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
        {
            "id": 2,
            "name": "Personal",
            "start": "Personal Out",
            "end": "Personal In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
        {
            "id": 3,
            "name": "Tea/Smoking",
            "start": "Tea/Smoking Out",
            "end": "Tea/Smoking In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
        {
            "id": 4,
            "name": "Official Work",
            "start": "Official Work Out",
            "end": "Official Work In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
        {
            "id": 5,
            "name": "Lunch",
            "start": "Lunch Out",
            "end": "Lunch In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
        {
            "id": 6,
            "name": "Prayer",
            "start": "Prayer Out",
            "end": "Prayer In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
        {
            "id": 7,
            "name": "Other",
            "start": "Other Out",
            "end": "Other In",
            "description": null,
            "created_at": "2020-06-09 12:52:50",
            "updated_at": "2020-06-09 12:52:50",
            "deleted_at": null,
            "icon": null,
            "start_color": null,
            "end_color": null,
        },
    ],
    "is_checkin_time": false,
    "checkin_time": "",
    "checkin_address": "",
    "is_checkout_time": false,
    "checkout_time": "",
    "checkout_address": "",
    "break_id": null,
    "is_break": false,
    "break_time": "",
    "is_pic_required": false,
    "shift": {
        "id": 3560,
        "created_at": "2024-01-01 06:43:16",
        "updated_at": "2024-01-01 06:43:16",
        "deleted_at": null,
        "employment_id": "d3e3bab8-a4c0-4ca1-9d84-b27ba4717305",
        "company_id": 1,
        "time_slot_id": 1,
        "date": "2024-11-11 00:00:00",
        "bg_colour": "#008f35",
        "font_colour": "#000000",
        "over_time_hours": 0,
        "start_datetime": "2024-11-11 04:00:00",
        "end_datetime": "2024-11-12 02:00:00",
        "department_hierarchy_code": "",
        "is_default": false,
        "expected_minutes": 540,
        "is_full_overtime_shift": false,
        "geo_fence_ids": [],
        "identifier": "20241111-d3e3bab8-a4c0-4ca1-9d84-b27ba4717305",
        "is_work_from_home": false,
        "is_optional": false,
        "shift_tags": [],
        "time_slot": {
            "id": 1,
            "code": "TS-00001",
            "day_changed": true,
            "start_buffer_minutes": 0,
            "end_buffer_minutes": 0,
            "punch_end_buffer_minutes": 59,
            "is_overtime_applicable": true,
            "is_active": true,
            "created_at": "2021-07-05 10:25:42",
            "updated_at": "2023-11-27 07:27:57",
            "deleted_at": null,
            "company_id": 1,
            "name": "General Timing ( Flexible Shift ) Short OT",
            "duration_minutes": 1320,
            "start": "2023-11-27 04:00:00",
            "end": "2023-11-28 02:00:00",
            "is_flexible": true,
            "flexible_minutes": 540,
            "bg_colour": "#008f35",
            "font_colour": "#000000",
            "is_full_overtime_slot": false,
            "is_night": false,
            "punch_start_buffer_minutes": 60,
            "flexible_hours": 9,
            "identifier": "TS-00001 - General Timing ( Flexible Shift ) Short OT (09:00 am - 07:00 am)",
            "status": "Active",
            "status_class": "bg-success",
        },
    },
    "geo_fences": [],
    "mark_checkin": true,
}

------WebKitFormBoundaryLlz6sJ56J5TaAiKJ--
"""


